<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Admin' => '',
    'Admin Panel' => '',
    'Are you sure you want to delete selected items?' => '',
    'Are you sure you want to delete this item?' => '',
    'BARCODE' => '',
    'CANCEL' => '',
    'CATEGORIES' => '',
    'CATEGORY' => '',
    'CREATED_AT' => '',
    'CREATE_CATEGORY' => '',
    'CREATE_PRODUCT' => '',
    'CREATE_USER' => '',
    'Cancel' => '',
    'Cancelled' => '',
    'Categories' => '',
    'Category' => '',
    'Content' => '',
    'Create' => '',
    'Create News' => '',
    'Created At' => '',
    'Created at' => '',
    'DELETED_AT' => '',
    'DELETED_CATEGORY' => '',
    'DESCRIPTION' => '',
    'Delete' => '',
    'Delete selected' => '',
    'FAVORITE' => '',
    'Full Name' => '',
    'Home' => '',
    'ID' => '',
    'IMAGE' => '',
    'INCOME_COUNT' => '',
    'INCOME_PRICE' => '',
    'IS_DELIVERY' => '',
    'Img' => '',
    'In process' => '',
    'Login' => '',
    'Menu' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Moderator' => '',
    'NOT_SET' => '',
    'New' => '',
    'New callback order from {phone}' => '',
    'New feedback from {name}' => '',
    'News' => '',
    'Orders' => '',
    'PARENT_CATEGORY' => '',
    'PRICE' => '',
    'PRODUCTS' => '',
    'PRODUCT_INCOME' => '',
    'Password' => '',
    'Phone' => '',
    'Price' => '',
    'Products' => '',
    'Reset' => '',
    'SAVE' => '',
    'STATUS' => '',
    'STATUS_ACTIVE' => '',
    'STATUS_INACTIVE' => '',
    'Save' => '',
    'Search' => '',
    'Sent' => '',
    'Slug' => '',
    'Status' => '',
    'TITLE' => '',
    'TYPE' => '',
    'The requested page does not exist.' => '',
    'Title' => '',
    'To admin panel.' => '',
    'UPDATE' => '',
    'UPDATED_AT' => '',
    'UPDATE_CATEGORY' => '',
    'UPDATE_PRODUCT' => '',
    'Update' => '',
    'Update News: mode' => '',
    'Updated At' => '',
    'Updated at' => '',
    'Welcome!' => '',
    'You need to select at least one item.' => '',
];
