<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Update settings' => 'Обновить настройку',
    'Update' => 'Обновить',
    'Settings' => 'Настройки',
    'name' => 'Лэйбл',
    'title' => 'Название',
    'value' => 'Значение',
    'Save' => 'Сохранить',
    'Create review' => 'Создать отзыв',

    'Reviews' => 'Отзывы',
    'Create reviews' => 'Создать отзыв',
    'Update reviews' => 'Обновить отзыв',
    'Update Review' => 'Обновить комментарий ',
    'Delete' => 'Удалить',
    'id' => 'ID',
    'fio' => 'Ф.И.О.',
    'content' => 'Контент',
    'product_id' => 'ID продукта',
    'status' => 'Статус',
    'created_at' => 'Создан',
    'updated_at' => 'Обновлен',


    'UPDATE' => 'Обновить',
    'DELETE' => 'Удалить',
    'SETTINGS' => 'Настройки',
    'UPDATE SETTINGS' => 'Обновить настройку',
    'CREATE SETTINGS' => 'Создать настройку',
    'Name' => 'Название',
    'Title' => 'Название',
    'Value' => 'Значение',

    'REVIEWS' => 'Отзывы',
    'UPDATE REVIEWS' => 'Обновить отзыв',
    'CREATE REVIEWS' => 'Создать отзыв',

    'SAVE' => 'Сохранить',
    'NOT PUBLISHED' => 'Не опубликовано',
    'PUBLISHED' => 'Опубликовано',
];
